### PR TITLE
[16.0][MIG] mis_builder_total_committed_purchase: Migration to 16.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Needs:
- https://github.com/OCA/mis-builder/pull/472

### CODE REVIEW

**Review by yankinmax — APPROVED** [review]

**Review by StephaneMangin — APPROVED** [review]

**Comment by yankinmax** [comment]
@sbidoul can we proceed on this, thx?

**Comment by sbidoul** [comment]
I have never used this module myself. But it seems this PR does not take the amounts in the analytic_distribution field into account. So it may not be correct, depending on the use case, unless exactly one analytic account is used in each analytic_distribution?

**Comment by dzungtran89** [comment]
Good day @yankinmax , I just updated the query to take the analytic distribution into account. So, when drilling down the details of committed, we will see the list of PO lines with the detailed distributed amount per analytic account

**Comment by yankinmax** [comment]
@sbidoul your remark is taken into account, thanks @dzungtran89

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
