### PR TITLE
[12.0][MIG] mis_builder_analytic

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by hitrosol** [comment]
I tested it in runbot and local, functionally okay. Thanks.

**Comment by marcelsavegnago** [comment]
ping @ernestotejeda

**Review by ernestotejeda — APPROVED** [review]
Code review 👍🏼

**Comment by marcelsavegnago** [comment]
> I tested it in runbot and local, functionally okay. Thanks.

@hitrosol If it's OK for you, please formalize approval by review. Thanks

image

**Review by hitrosol — APPROVED** [review]
LGTM

**Review by rvalyi — APPROVED** [review]

**Comment by rvalyi** [comment]
I used it as well in v12 projects, it's useful to track timesheet costs for instance.

**Pull request merged**
