### PR TITLE
[14.0][MIG] mis_builder_total_committed_purchase: Migration to 14.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
cc @douglascstd @augustodinizl @aug1804 @rodrigonevest

**Review by marcelsavegnago — APPROVED** [review]

**Review by rodrigonevest — APPROVED** [review]
LGTM

**Comment by marcelsavegnago** [comment]
cc @douglascstd @augustodinizl @aug1804

**Comment by augustodinizl** [comment]
LGTM

**Comment by aug1804** [comment]
It looks good to me too.

**Comment by kaynnan** [comment]
ping @OCA/mis-builder-maintainers

**Comment by marcelsavegnago** [comment]
@augustodinizl @aug1804 I saw that you made comments in the PR at first approving the PR. Can you officially do this?

image

**Review by aug1804 — APPROVED** [review]
I forgot the approval, sorry.

**Pull request closed without merging**
