### PR TITLE
[15.0][MIG] mis_builder_analytic: Migration to 15.0 

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
cc @douglascstd @augustodinizl @aug1804 @rodrigonevest

**Review by augustodinizl — APPROVED** [review]
LGTM - functional tests working as expected - OK

Screenshot at Jun 20 20-53-50

Screenshot at Jun 20 20-56-31

**Comment by marcelsavegnago** [comment]
ping @rvalyi

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@kaynnan Kaynnan opens PR by migrating to 16 please

**Pull request closed without merging**
