### PR TITLE
[14.0][MIG] mis_builder_analytic

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by hitrosol** [comment]
I try this in runboat, and it works well.

**Comment by marcelsavegnago** [comment]
ping @rvalyi @douglascstd @augustodinizl

**Review by rvalyi — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/mis-builder-maintainers

**Comment by marcelsavegnago** [comment]
ping @douglascstd

**Review by felipemotter — APPROVED** [review]

**Review by stefano-ooops — APPROVED** [review]
lgtm

**Comment by elvise** [comment]
@pedrobaeza looks ready for merge, what do you think?

**Comment by pedrobaeza** [comment]
GH actions is down: https://www.githubstatus.com/

**Review by douglascstd — APPROVED** [review]
[APPROVED] Functional Tests have been made.

**Using a vendor bill**
image

image

image

**Note:** To work, all the analytic items must have a liked account, otherwise you couldn't retrive the value to apply in your report.

Follow the test to use an analytic entry without an acccount linked.
Create the analytic entry (with a specific product linked)
image

The error:
image

**Comment by hitrosol** [comment]
I try this again in runboat after merged. 
I see now the result is different than previous one. 
If I set the report like this:
image

then the result will be like this: 
image

In previous version, the detail display by account will show the Analytical Account instead of the Account, like this:
image


My understanding, having MIS Account Analytic Line as Move Line Source, will use Analytical Account as source so, we can show the Analytical Account as detail.

**Pull request merged**
