### PR TITLE
[15.0] [mig] mis_builder_budget_tier_validation

### PR DESCRIPTION
**Pull request by aktiv-heli-kantawala**

### CODE REVIEW

**Review by misern2 — COMMENTED** [review]
Pre-commit is red. Can you check it, please?

**Comment by aktiv-heli-kantawala** [comment]
> Pre-commit is red. Can you check it, please?

I have done the changes and commit it. Please check it.

**Comment by rafaelbn** [comment]
Please @misern2 can you review ? you comments were attended. Thank you! 😄

**Pull request closed without merging**
